### PR TITLE
Make @folio/users a peerDependency instead of a dependency.

### PR DESCRIPTION
**Pull request by wafschneider**
Resolves STRIPES-478.

### CODE REVIEW

**Comment by wafschneider** [comment]
See discussion in https://issues.folio.org/browse/STRIPES-478 -- perhaps it is legitimate for the plugin to depend directly on `@folio/users`.

**Comment by zburke** [comment]
In light of [further discussion on that issue](https://issues.folio.org/browse/STRIPES-478?focusedCommentId=21110&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-21110), I think we do in fact want to merge this PR. 

> "peerDependency" is like telling NPM, "Use the global instance of this package, or create a global instance of this package if there isn't one already."

A peerDependency is a hard dependency and will cause the depended-on package to be pulled into the bundle if a compatible version is not already there, or will cause the build to fail if another package peer-depends on an incompatible version.

**Comment by skomorokh** [comment]
Pretty sure a peer dependency explicitly does not get pulled in if absent. As it would be if the Users app is not in use (eg. a third party replacement is instead) but still being relied on to provide the plugin functionality.

**Comment by MikeTaylor** [comment]
That was what I thought, @skomorokh; but Zak looked into this and apparently found the opposite.

**Comment by zburke** [comment]
Let me do some more research to be certain that what I did will be applicable in a production build environment. "This one developer tried it on his machine one time and he says it worked." is not the kind of statement I would bet my life on.

**Comment by zburke** [comment]
Finally closing this in light of #70.

**Pull request closed without merging**
